# Default values for metrics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  images:
    influxdb2: influxdb:2.3.0
    grafana: grafana/grafana:9.0.3